#!/bin/sh
open 'https://docs.google.com/spreadsheets/d/18sBp6l7aA6twYE9lMv_qapnvtPThm-i9TeVj9lCcnZs/edit#gid=0'
open 'https://docs.google.com/spreadsheets/d/1JFzorhcHClCd2jcQahJ1pzxWOYM_L_y57TqbnRY_p1Q/edit#gid=0'
