#!/usr/bin/env bash
mvn integration-test -e -Dmaven.javadoc.skip=true -Ddependency-check.skip=true -Dlicenses.skip=true -DfailIfNoTests=false -Dtest=$1 -pl com.cerner.cloud.idm.system:system-accounts-itests
